### ISSUE TITLE
Consider repo name change

### ISSUE THREAD

**Issue by filmaj** [adobe/research-datasets#3]
Having "adobe" in the name of the repo doesn't make sense if it will continue to exist under the Adobe org. Also just "datasets" on its own is too generic.

It would be nice to have a short, single-sentence summary of the project, to put right at the top of the README as well as into the project description field (so that when users are browsing the repository list on github.com/adobe, they can see a brief description from the list).

Any thoughts or recommendations on this @pppoe ?

**Comment by pppoe** [comment]
@filmaj How about research-datasets? "Datasets Contributed by Adobe to the Research Community". BTW, I'd like to clarify that I already left Adobe about 2 months ago :)

**Comment by filmaj** [comment]
@pppoe I see, yes, that would be why you don't have push access. Hmm. What team were you a part of? Would you mind emailing any information about your prior team, manager, teammates, anything like that to me at maj@adobe.com ? I will follow up with them to see about ownership of this repo and that kind of stuff. And this way I can stop bothering you :)

**Comment by jimmie33** [comment]
I have re-named the project name and added description under the title.
